# permissions for end users to edit wordpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubepress
    app.kubernetes.io/managed-by: kustomize
  name: wordpress-editor-role
rules:
- apiGroups:
  - crm.hostzero.de
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crm.hostzero.de
  resources:
  - wordpresses/status
  verbs:
  - get
